import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Script from 'next/script'
import { Suspense } from 'react'
//import Loading from './Loading'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <title>Villa Agency - Real Estate HTML5 Template</title>

        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

        <link rel="stylesheet" href="/assets/css/fontawesome.css" />
        <link rel="stylesheet" href="/assets/css/templatemo-villa-agency.css" />
        <link rel="stylesheet" href="/assets/css/owl.css" />
        <link rel="stylesheet" href="/assets/css/animate.css" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
        />
      </head>
      <body>
                <Suspense fallback={<Loading/>}>

        <Navbar />
        {children}
        <Footer />
        </Suspense>
        <Script src="vendor/jquery/jquery.min.js"/>
        <Script src="vendor/bootstrap/js/bootstrap.min.js"/>
        <Script src="assets/js/isotope.min.js"/>
        <Script src="assets/js/owl-carousel.js"/>
        <Script src="assets/js/counter.js"/>
        <Script src="assets/js/custom.js"/>
      </body>
    </html>
  );
}